-- Actualizar tabla conversaciones con campos de seguimiento
ALTER TABLE conversaciones 
ADD COLUMN IF NOT EXISTS estado TEXT DEFAULT 'nuevo',
ADD COLUMN IF NOT EXISTS nombre TEXT,
ADD COLUMN IF NOT EXISTS negocio TEXT,
ADD COLUMN IF NOT EXISTS fecha_ultimo_mensaje TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS fecha_ultimo_evento TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS seguimientos JSONB DEFAULT '[]',
ADD COLUMN IF NOT EXISTS contador_seguimientos INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS caliente BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS bot_enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS categoria TEXT,
ADD COLUMN IF NOT EXISTS prioridad TEXT,
ADD COLUMN IF NOT EXISTS score TEXT,
ADD COLUMN IF NOT EXISTS total_fugas TEXT,
ADD COLUMN IF NOT EXISTS fugas_detectadas TEXT,
ADD COLUMN IF NOT EXISTS rating TEXT,
ADD COLUMN IF NOT EXISTS resenas TEXT,
ADD COLUMN IF NOT EXISTS fotos TEXT,
ADD COLUMN IF NOT EXISTS fotos_estimadas TEXT,
ADD COLUMN IF NOT EXISTS diagnostico_fotos TEXT,
ADD COLUMN IF NOT EXISTS ultima_resena TEXT,
ADD COLUMN IF NOT EXISTS responde_resenas TEXT,
ADD COLUMN IF NOT EXISTS publicaciones TEXT,
ADD COLUMN IF NOT EXISTS website TEXT,
ADD COLUMN IF NOT EXISTS horarios TEXT,
ADD COLUMN IF NOT EXISTS descripcion TEXT,
ADD COLUMN IF NOT EXISTS whatsapp_link TEXT,
ADD COLUMN IF NOT EXISTS direccion TEXT,
ADD COLUMN IF NOT EXISTS maps_url TEXT,
ADD COLUMN IF NOT EXISTS ultimo_mensaje TEXT,
ADD COLUMN IF NOT EXISTS mensaje_inicial_enviado BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS notas TEXT,
ADD COLUMN IF NOT EXISTS proxima_accion TEXT,
ADD COLUMN IF NOT EXISTS fecha_seguimiento TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS seguimiento_activo BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS motivo_seguimiento TEXT,
ADD COLUMN IF NOT EXISTS resultado_conversacion TEXT,
ADD COLUMN IF NOT EXISTS objecion_principal TEXT,
ADD COLUMN IF NOT EXISTS etapa_perdida TEXT,
ADD COLUMN IF NOT EXISTS ultima_accion_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS ultimo_recordatorio_at TIMESTAMP WITH TIME ZONE;

-- Tabla de tareas para Juan Carlos
CREATE TABLE IF NOT EXISTS tareas (
  id SERIAL PRIMARY KEY,
  telefono TEXT NOT NULL,
  tipo TEXT NOT NULL,
  mensaje TEXT,
  fecha_programada DATE NOT NULL,
  completada BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para el cron
CREATE INDEX IF NOT EXISTS idx_conversaciones_estado ON conversaciones(estado);
CREATE INDEX IF NOT EXISTS idx_conversaciones_caliente ON conversaciones(caliente);
CREATE INDEX IF NOT EXISTS idx_tareas_fecha ON tareas(fecha_programada, completada);

-- Tabla de mensajes para CRM ON
CREATE TABLE IF NOT EXISTS mensajes (
  id SERIAL PRIMARY KEY,
  telefono TEXT NOT NULL,
  direccion TEXT NOT NULL,
  mensaje TEXT NOT NULL,
  raw JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mensajes_telefono_created_at ON mensajes(telefono, created_at);

CREATE TABLE IF NOT EXISTS eventos_crm (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telefono TEXT NOT NULL,
  tipo TEXT NOT NULL,
  descripcion TEXT,
  metadata JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_eventos_crm_telefono_created_at ON eventos_crm(telefono, created_at);
CREATE INDEX IF NOT EXISTS idx_conversaciones_fecha_seguimiento ON conversaciones(fecha_seguimiento, seguimiento_activo);

CREATE OR REPLACE VIEW conversaciones_resumen AS
WITH mensaje_stats AS (
  SELECT
    telefono,
    COUNT(*)::INTEGER AS total_mensajes,
    COUNT(*) FILTER (WHERE direccion = 'entrante')::INTEGER AS mensajes_entrantes,
    COUNT(*) FILTER (WHERE direccion = 'saliente')::INTEGER AS mensajes_salientes,
    MAX(created_at) AS fecha_ultimo_mensaje_real,
    MAX(created_at) FILTER (WHERE direccion = 'saliente') AS fecha_ultima_respuesta
  FROM mensajes
  GROUP BY telefono
),
ultimo AS (
  SELECT DISTINCT ON (telefono)
    telefono,
    direccion AS direccion_ultimo_mensaje,
    mensaje AS texto_ultimo_mensaje,
    created_at AS fecha_ultimo_mensaje_real
  FROM mensajes
  ORDER BY telefono, created_at DESC, id DESC
),
pendientes AS (
  SELECT
    m.telefono,
    COUNT(*)::INTEGER AS mensajes_pendientes
  FROM mensajes m
  LEFT JOIN mensaje_stats s ON s.telefono = m.telefono
  WHERE m.direccion = 'entrante'
    AND m.created_at > COALESCE(s.fecha_ultima_respuesta, '1970-01-01'::timestamptz)
  GROUP BY m.telefono
)
SELECT
  c.*,
  COALESCE(s.total_mensajes, 0) AS total_mensajes,
  COALESCE(s.mensajes_entrantes, 0) AS mensajes_entrantes,
  COALESCE(s.mensajes_salientes, 0) AS mensajes_salientes,
  COALESCE(u.fecha_ultimo_mensaje_real, c.fecha_ultimo_mensaje) AS fecha_ultimo_mensaje_real,
  u.direccion_ultimo_mensaje,
  u.texto_ultimo_mensaje,
  COALESCE(p.mensajes_pendientes, 0) AS mensajes_pendientes,
  (
    u.direccion_ultimo_mensaje = 'entrante'
    AND COALESCE(p.mensajes_pendientes, 0) > 0
  ) AS mensaje_nuevo
FROM conversaciones c
LEFT JOIN mensaje_stats s ON s.telefono = c.telefono
LEFT JOIN ultimo u ON u.telefono = c.telefono
LEFT JOIN pendientes p ON p.telefono = c.telefono;
